spring:
  datasource:
    username: jruser
    password: jruser
    url: jdbc:postgresql://localhost:5432/testdb
    hikari:
      driver-class-name: "org.postgresql.Driver"
  jpa:
    properties:
     hibernate:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"