spring:
  datasource:
    username: jruser
    password: jruser
    url: jdbc:postgresql://localhost:5432/testdb
    hikari:
      driver-class-name: "org.postgresql.Driver"
  jpa:
    properties:
     hibernate:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
      jdbc.lob.non_contextual_creation: true

redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
